apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerchurn-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customerchurn-app
  template:
    metadata:
      labels:
        app: customerchurn-app
    spec:
      containers:
        - name: customerchurn-app
          image: wededo4644/customerchurn:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8501
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "512Mi"
