apiVersion: v1
kind: Service
metadata:
  name: customerchurn-app
spec:
  type: NodePort
  selector:
    app: customerchurn-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 31001